### ISSUE TITLE
Падает сборка, если в стилях есть blockquote

### ISSUE THREAD

**Issue by gela-d** [enb-make/enb-stylus#30]
Если в коде есть такая конструкция
```css
.a
{
    color: black;
 
    blockquote 
    {
        color: red;
    }
}
 ```
то при сборке, падает на ошибке
`Cannot read property 'block' of undefined`

Если расширить запись, то все ок:
```css
.a 
{
    color: black;
}
 
.a blockquote 
{
    color: red;
}
```
________________
Используем enb-stylys@1.2.2
