### ISSUE TITLE
Didn`t add a CSS comment to files with a custom suffix

### ISSUE THREAD

**Issue by tavriaforever** [enb-make/enb-stylus#95]
1. Block have `styl` file with custom suffix:
```
* blocks/
├── block.styl
├── block.ie.styl
└── block.css
```
2. **Run** tech with option `{ sourceSuffixes: ['styl', 'css', 'ie.styl'] }`
3. **Result:** 
```css
/* ../blocks/block.styl:begin */
.icon {
  width: 200px;
}
/* ../blocks/block.styl:end */
.icon
{
    color: #fff;
}
```
So, if `styl` file have custom suffix, in this case comments did not add.
